### ISSUE TITLE
Implement support for managing and tracking images

### ISSUE THREAD

**Issue by xprnio** [xprnio/go-serverless#4]
It should be possible to both manage and track images used within the system.

- [ ] Listing all images
- [ ] Pulling images
- [ ] Labeling images when pulled
  To indicate that an image is used as a function, a label should be added to it
- [ ] Getting image details
  Since multiple versions of an image can exist, all versions should be included in the details
- [ ] Pulling private images
  Since images can be private, authentication should be supported on an image level
